# These are supported funding model platforms

github: [bayudwiyansatria]
patreon: bayudwiyansatria
open_collective: bayudwiyansatria
ko_fi: bayudwiyansatria
tidelift: npm/bayudwiyansatria
custom: https://bayudwiyansatria.com
